#ifndef SWF_TAGS_H
#define SWF_TAGS_H

namespace swf_redux
{
enum {
    SwfTag_End					= 0,
    SwfTag_ShowFrame			= 1,
    SwfTag_DefineShape			= 2,
    SwfTag_PlaceObject			= 4,
    SwfTag_RemoveObject			= 5,
    SwfTag_DefineButton			= 7,
    SwfTag_SetBackgroundColor	= 9,
    SwfTag_DefineFont           = 10,
    SwfTag_DefineText           = 11,
    SwfTag_DoAction             = 12,
    SwfTag_DefineFontInfo		= 13,
    SwfTag_DefineSound			= 14,
    SwfTag_StartSound			= 15,
    SwfTag_DefineButtonSound	= 17,
    SwfTag_SoundStreamHead		= 18,
    SwfTag_SoundStreamBlock		= 19,
    SwfTag_DefineBitsJPEG2		= 21,
    SwfTag_DefineShape2         = 22,
    SwfTag_DefineButtonCxform	= 23,
    SwfTag_Protect				= 24,
    SwfTag_PlaceObject2			= 26,
    SwfTag_RemoveObject2		= 28,
    SwfTag_DefineShape3         = 32,
    SwfTag_DefineText2			= 33,
    SwfTag_DefineButton2        = 34,
    SwfTag_DefineBitsJPEG3		= 35,
    SwfTag_DefineEditText		= 37,
    SwfTag_DefineSprite         = 39,
    SwfTag_FrameLabel			= 43,
    SwfTag_SoundStreamHead2		= 45,
    SwfTag_DefineMorphShape		= 46,
    SwfTag_DefineFont2			= 48,
    SwfTag_ExportAssets         = 56,
    SwfTag_ImportAssets         = 57,
    SwfTag_EnableDebugger       = 58,
    SwfTag_EnableDebugger2      = 64,
    SwfTag_ScriptLimits         = 65,
    SwfTag_FileAttributes		= 69,
    SwfTag_PlaceObject3			= 70,
    SwfTag_DefineFontAlignZones = 73,
    SwfTag_CSMTextSettings		= 74,
    SwfTag_DefineFont3			= 75,
    SwfTag_SymbolClass			= 76,
    SwfTag_MetaData				= 77,
    SwfTag_DoABC				= 82,
    SwfTag_DefineShape4         = 83,
    SwfTag_DefineMorphShape2	= 84,
    SwfTag_DefineSceneAndFrameLabelData = 86,
    SwfTag_DefineFontName		= 88,
    SwfTag_StartSound2			= 89,
    SwfTag_DefineFont4			= 91,
};

} // namespace swf_redux

#endif